### PR TITLE
Adding fingerprintCollector

### PR DESCRIPTION
**Pull request by pruzanov**
In this commit:

- Added fingerprintCollector pulled workflow
- Fixed README.md
- Added missing metadata
- changed the Regression Tests to account for added FC

### CODE REVIEW

**Comment by pruzanov** [comment]
retest this please

**Comment by pruzanov** [comment]
retest this please

**Comment by pruzanov** [comment]
retest this please

**Comment by pruzanov** [comment]
retest this please

**Review by asofmosq — APPROVED** [review]

**Pull request merged**
